export const geoDataDefaults = {
  mineInfo: null,
  strata: [],
  coalSeams: [],
  boreholes: [],
  faults: [],
  collapseColumns: [],
  workingFaces: [],
  tunnels: [],
  miningPaths: [],
  aquifers: [],
  goafWaterAreas: [],
  waterInrushPoints: [],
  waterRichAreas: [],
  gasRichAreas: [],
  gasContentPoints: [],
  gasPressurePoints: [],
  softLayers: [],
  smallMineDamageAreas: [],
  goafAreas: [],
  abandonedShafts: [],
  poorSealedBoreholes: [],
  faultInfluenceZones: [],
  warningPoints: [],
  riskRanges: [],
  measurePoints: [],
  riskBodies: [],
};
